default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: majedbojan122
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_spreedsheet_development
